### ISSUE TITLE
ヘッダーの開閉メニュー作成

### ISSUE THREAD

**Issue by antyoku** [Update-hub/stage-2-antyoku#35]
![38762729-1431a706-3fca-11e8-8ad6-4b2adfde178f](https://user-images.githubusercontent.com/36844789/39225693-b721342e-4888-11e8-80e3-98891aa0dee1.png)

[開いた後の画面](https://xd.adobe.com/spec/2c5a7649-2461-4f24-7604-68a12268ca0f-5a6b/#screen/105eb7e1-c654-424f-a3c5-c46ed6e1860e/SP%20-%20menu)

- アイコンクリック(タップ)でメニューが開閉する
- 開閉の動きはcssアニメーションを用いる
- 動き、アニメーションイメージは下記サイトを概ね踏襲してください。developer tool でスマホモードで閲覧してください。
https://firebase.google.com/?hl=ja

**Comment by rsmgcp** [comment]
スマホのナビが開いた状態で、ロゴタッチした場合、何も起きない仕様でしょうか？
それ以外はきになる点がありませんでしたので、このままで良かったらマージします。
