### ISSUE TITLE
validetorチェックを通るよう修正

### ISSUE THREAD

**Issue by antyoku** [Update-hub/stage-2-antyoku#60]
#41 より

HTMLvalidator（ https://validator.w3.org/ ）にて以下のエラーが出ています。修正をお願いします。

- \<heading\>というタグを使用している。
→heading.pugの```heading.heading```を```.heading```に変更。
- popularセクションにおいて見出しタグが使用されていない。
→popular-card.pugの```.card__name```に見出しタグを付与（```h1```は1ページに1つというルールがあるので```h2```以下にしてください）。
- MEDIAセクションにおいて```allow```属性の設定が不適切。また、HTML5では廃止になった```frameborder```が使われている。
→前者は調べてください（すみません）。後者はCSSの```border```で代替してください。

**Comment by hakuoku** [comment]
担当いたします。
