### ISSUE TITLE
section scss見直し

### ISSUE THREAD

**Issue by deerboy** [Update-hub/stage-2-antyoku#81]
https://github.com/Update-hub/stage-2-antyoku/blob/75f1a0fd1df42682ee8dc3ae8f23ffbb89e5a07c/src/scss/components/_section.scss#L14

こいつも上のスコープに含めて良い

**Comment by rsmgcp** [comment]
.section--limited　現在どのセクションでも使われていいないので、削除してもいいですか？

**Comment by rsmgcp** [comment]
対応します。
